import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { AlertOctagon, Search, RefreshCw, ArrowUpRight, Cpu, ShieldAlert } from 'lucide-react';
import { alertsAPI } from '../services/api';
import { SeverityBadge } from '../components/common/SeverityBadge';

export const AlertsPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [severityFilter, setSeverityFilter] = useState('All');

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const res = await alertsAPI.list({
        search: search || undefined,
        severity: severityFilter !== 'All' ? severityFilter : undefined,
      });
      setAlerts(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [severityFilter]);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    fetchAlerts();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold font-mono tracking-wide text-slate-100 flex items-center gap-2">
            <AlertOctagon className="w-5 h-5 text-orange-400" />
            ML DETECTION ALERTS
          </h1>
          <p className="text-xs text-slate-400 mt-0.5">
            Security alerts generated by supervised Random Forest & unsupervised Isolation Forest models
          </p>
        </div>
        <button
          onClick={fetchAlerts}
          className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 rounded-lg text-xs font-mono flex items-center gap-1.5 transition-colors self-start md:self-auto"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          <span>Refresh Alerts</span>
        </button>
      </div>

      {/* Filter */}
      <div className="soc-card p-4">
        <form onSubmit={handleSearchSubmit} className="flex flex-col md:flex-row gap-3 items-center">
          <div className="relative flex-1 w-full">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-2.5" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by Alert ID, attack type, origin IP or device..."
              className="w-full bg-slate-900 border border-slate-700 rounded-lg pl-9 pr-3 py-1.5 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-blue-500 font-mono"
            />
          </div>

          <div className="flex items-center gap-2 w-full md:w-auto">
            <select
              value={severityFilter}
              onChange={(e) => setSeverityFilter(e.target.value)}
              className="bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 font-mono focus:outline-none focus:border-blue-500"
            >
              <option value="All">All Severities</option>
              <option value="Critical">Critical</option>
              <option value="High">High</option>
              <option value="Medium">Medium</option>
              <option value="Low">Low</option>
            </select>

            <button
              type="submit"
              className="px-4 py-1.5 bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 border border-blue-500/40 rounded-lg text-xs font-mono shrink-0"
            >
              Filter
            </button>
          </div>
        </form>
      </div>

      {/* Alerts Table */}
      <div className="soc-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead className="bg-slate-900/80 text-[11px] text-slate-400 uppercase border-b border-slate-800">
              <tr>
                <th className="py-3 px-4">Alert ID</th>
                <th className="py-3 px-4">Classified Attack Type</th>
                <th className="py-3 px-4">Severity</th>
                <th className="py-3 px-4">ML Confidence</th>
                <th className="py-3 px-4">Origin IP</th>
                <th className="py-3 px-4">Target Device</th>
                <th className="py-3 px-4">Trigger Time (UTC)</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4 text-right">Correlated Incident</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800 text-xs">
              {loading && alerts.length === 0 ? (
                <tr>
                  <td colSpan="9" className="py-8 text-center text-slate-500">
                    Loading ML alert telemetry...
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan="9" className="py-8 text-center text-slate-500">
                    No alerts found.
                  </td>
                </tr>
              ) : (
                alerts.map((alert) => (
                  <tr key={alert.id} className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-3 px-4 text-orange-400 font-bold">{alert.alert_id}</td>
                    <td className="py-3 px-4 text-slate-200 flex items-center gap-1.5">
                      <Cpu className="w-3.5 h-3.5 text-blue-400 shrink-0" />
                      <span>{alert.attack_type}</span>
                    </td>
                    <td className="py-3 px-4">
                      <SeverityBadge severity={alert.severity} />
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-2">
                        <div className="w-14 bg-slate-800 rounded-full h-1.5 overflow-hidden">
                          <div 
                            className="bg-orange-500 h-full rounded-full" 
                            style={{ width: `${Math.round((alert.confidence || 0.8) * 100)}%` }} 
                          />
                        </div>
                        <span className="text-slate-300 text-[11px] font-bold">
                          {Math.round((alert.confidence || 0.8) * 100)}%
                        </span>
                      </div>
                    </td>
                    <td className="py-3 px-4 text-cyan-400">{alert.source}</td>
                    <td className="py-3 px-4 text-slate-300">{alert.device}</td>
                    <td className="py-3 px-4 text-slate-400 text-[11px]">
                      {alert.timestamp?.slice(11, 19) || alert.timestamp}
                    </td>
                    <td className="py-3 px-4">
                      <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-500/10 text-amber-400 border border-amber-500/20">
                        {alert.status}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-right">
                      {alert.incident_id ? (
                        <Link
                          to={`/incidents/${alert.incident_id}`}
                          className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-blue-500/10 hover:bg-blue-500/20 text-blue-300 border border-blue-500/30 text-[11px] font-bold transition-colors"
                        >
                          <span>{alert.incident_id}</span>
                          <ArrowUpRight className="w-3 h-3" />
                        </Link>
                      ) : (
                        <span className="text-slate-600">Uncorrelated</span>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
